- web/web_ui/src/main/webapp/projects/projectjobqueue.xhtml
- web/web_ui/src/main/webapp/projects/projectview.xhtml
> added confirmation dialogue for job queue kills and deletes

- proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/Main.java
- proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/ajp/AJPClient.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/EmbeddedProxy.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/Main.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/ProxyApp.java
Set unlimited connection timeout
Increased the accepted response size from 1MB to 4MB
title: - Changes needed for issues encountered in Canada
The proxy was timing-out a slow response (longer than ~24 sec). We should not need that since we can deal with slow responses in the browser.
The PDF prints for Canada can be above the 1MB limit and the proxy just skips recording them. Increased it to 4MB.
> Set unlimited connection timeout; Increased the recorded response size from 1MB to 4MB;

- agent/agent_standalone/pom.xml
- agent/agent_standalone/src/main/java/com/intuit/tank/standalone/agent/CommandListener.java
- agent/apiharness/pom.xml
- agent/apiharness/src/main/java/com/intuit/tank/harness/CommandListener.java
- pom.xml
> upgrade simpleframework 4.1.21 -> 6.0.1

- data_access/src/main/java/com/intuit/tank/dao/TransactionContainer.java
- data_access/src/main/resources/META-INF/persistence.xml
- pom.xml
> Upgrade Hibernate 4.2.21 -> 5.2.16

- pom.xml
- search/document_util/src/main/java/com/intuit/tank/search/util/FieldSearchParam.java
- search/document_util/src/main/java/com/intuit/tank/search/util/MultiSearchParam.java
- search/document_util/src/main/java/com/intuit/tank/search/util/MustNotFieldSearchParam.java
- search/document_util/src/main/java/com/intuit/tank/search/util/SearchConstants.java
- search/document_util/src/main/java/com/intuit/tank/search/util/SearchQuery.java
- search/document_util/src/main/java/com/intuit/tank/search/util/SearchUtils.java
- search/document_util/src/main/java/com/intuit/tank/search/util/TankAnalyzer.java
- search/document_util/src/test/java/com/intuit/tank/search/util/FieldSearchParamTest.java
- search/document_util/src/test/java/com/intuit/tank/search/util/MustNotFieldSearchParamTest.java
- search/document_util/src/test/java/com/intuit/tank/search/util/SearchQueryTest.java
- search/document_util/src/test/java/com/intuit/tank/search/util/TankAnalyzerTest.java
- search/lucene_indexer/src/main/java/com/intuit/tank/search/lucene/LuceneService.java
- search/lucene_indexer/src/test/java/com/intuit/tank/search/lucene/LuceneServiceTest.java
- search/script_search/src/main/java/com/intuit/tank/search/script/ScriptSearchService.java
> Security Issue Resolved [CVE-2017-12629, CVE-2019-0199, CVE-2019-0232]

- rest/service/cloud/src/main/java/com/intuit/tank/service/impl/v1/cloud/JobController.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/AgentWatchdog.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/VMTrackerImpl.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/IEnvironmentInstance.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/VMChannelImpl.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
> Async kill/stop instances

- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/WorkLoadFactory.java
- web/web_ui/src/main/webapp/projects/workloadScripts.xhtml
> Thread start behavior

- agent/agent_common/pom.xml
- api/pom.xml
- data_model/pom.xml
- pom.xml
- proxy-parent/owasp-proxy/pom.xml
- reporting/pom.xml
- rest/api/datafile/pom.xml
- rest/api/pom.xml
- rest/pom.xml
- search/document_util/pom.xml
- tools/pom.xml
- web/web_ui/pom.xml
> Dependency clean up

- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
- tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/AgentDebuggerFrame.java
> Fix TestPlanStarter to honor simulationTime & agent debugger

- data_access/src/main/resources/META-INF/persistence.xml
- data_access/src/test/resources/META-INF/persistence.xml
- data_model/src/main/java/com/intuit/tank/project/TankDefaultRevisionEntity.java
- data_model/src/main/java/com/intuit/tank/project/TankRevisionInfo.java
- data_model/src/main/java/com/intuit/tank/project/TankRevisionListener.java
- data_model/src/test/java/com/intuit/tank/project/TankRevisionInfoTest.java
- data_model/src/test/java/com/intuit/tank/project/TankRevisionListenerTest.java
- pom.xml
- web/web_support/src/test/resources/META-INF/persistence.xml
> Hibernate version update to [5.1.17.Final]

- agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java
- agent/http_client_5/src/main/java/com/intuit/tank/httpclient5/TankHttpClient5.java
> Set UserToken on HttpClient Context

- rest/api/automation/src/main/java/com/intuit/tank/api/model/v1/automation/CreateJobRequest.java
- rest/service/automation/src/main/java/com/intuit/tank/service/impl/v1/automation/AutomationServiceV1.java
> Vm instance

- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/logging/ThreadLocalLogEvent.java
- api/src/main/java/com/intuit/tank/harness/AmazonUtil.java
- buildspec.yml
- pom.xml
> Logging + Library updates

- data_access/src/test/java/com/intuit/tank/dao/DaoTestUtil.java
- data_access/src/test/java/com/intuit/tank/dao/DataFileDaoTest.java
- data_access/src/test/java/com/intuit/tank/dao/GroupDaoTest.java
- data_access/src/test/java/com/intuit/tank/dao/JobRegionDaoTest.java
- data_access/src/test/java/com/intuit/tank/dao/PeriodicDataTest.java
- data_access/src/test/java/com/intuit/tank/dao/UserDaoTest.java
- data_model/src/main/java/com/intuit/tank/project/DataFile.java
- data_model/src/main/java/com/intuit/tank/project/Group.java
- data_model/src/main/java/com/intuit/tank/project/JobConfiguration.java
- data_model/src/main/java/com/intuit/tank/project/JobRegion.java
- data_model/src/main/java/com/intuit/tank/project/PeriodicData.java
- data_model/src/main/java/com/intuit/tank/project/User.java
title: - More test cases & code coverage for issue #88, 
> More test cases & code coverage for issue #88

- data_model/src/test/java/com/intuit/tank/util/CreateDateComparatorTest.java
- data_model/src/test/java/com/intuit/tank/util/DataFileUtilTest.java
title: - Improving test coverage in data-model module issue #88 
> Improving test coverage in data-model module

- data_model/src/test/java/com/intuit/tank/project/ProjectDTOTest.java
- data_model/src/test/java/com/intuit/tank/project/RevisionedEntityTest.java
- data_model/src/test/java/com/intuit/tank/project/SummaryDataBuilderTest.java
- data_model/src/test/java/com/intuit/tank/project/TankDefaultRevisionEntityTest.java
title: - Improving test coverage for data-model project module issue #88 
> Improving test coverage for data-model project module

- agent/agent_startup/src/main/java/com/intuit/tank/agent/AgentStartup.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/test/java/com/intuit/tank/common/TPSTest.java
- api/pom.xml
- api/src/main/java/com/intuit/tank/storage/S3FileStorage.java
- api/src/main/java/com/intuit/tank/vm/common/PasswordEncoder.java
- api/src/test/java/com/intuit/tank/vm/common/util/MethodTimerCpTest.java
- pom.xml
- proxy-parent/proxy_pkg/pom.xml
- reporting/db/pom.xml
- reporting/db/src/main/java/com/intuit/tank/persistence/databases/AmazonDynamoDatabaseDocApi.java
- reporting/db/src/main/java/com/intuit/tank/persistence/databases/CloudWatchDataSource.java
- reporting/db/src/main/java/com/intuit/tank/persistence/databases/S3Datasource.java
- reporting/db/src/test/java/com/intuit/tank/persistence/databases/AmazonDynamoDatabaseTest.java
- tank_vmManager/pom.xml
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/IEnvironmentInstance.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonDataConverter.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonS3.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/CloudwatchInstance.java
- tank_vmManager/src/test/java/com/intuit/tank/vmManager/environment/amazon/AmazonDataConverterTest.java
- tools/agent_debugger_pkg/pom.xml
- tools/script_filter/pom.xml
- web/web_ui/pom.xml
> AWS SDK V2

- agent/apiharness/pom.xml
- api/src/test/java/com/intuit/tank/harness/AmazonUtilTest.java
> Fix artifact rename

- web/web_ui/src/main/webapp/filters/index.xhtml
Filter Page Search: - TANK's Filter Page search bar pointing to nonexistent filter function
> Filter Page: Fix Search Bar Bug

- web/web_support/src/main/java/com/intuit/tank/job/ActJobNodeBean.java
- web/web_support/src/main/java/com/intuit/tank/job/JobNodeBean.java
- web/web_support/src/main/java/com/intuit/tank/job/JobStatusHelper.java
- web/web_support/src/main/java/com/intuit/tank/job/ProjectNodeBean.java
- web/web_support/src/main/java/com/intuit/tank/job/VMNodeBean.java
- web/web_ui/src/main/webapp/agents/index.xhtml
- web/web_ui/src/main/webapp/projects/projectjobqueue.xhtml
Disable delete job button right after a job starts
> implement isDeleteable [SRE-19307]

- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/AgentRunData.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
- agent/apiharness/src/main/java/com/intuit/tank/runner/TestPlanRunner.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/AgentRunDataTest.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/TestPlanStarterTest.java
Ramp Time Mismatch: - Expected ramp time not being met due to inaccurate thread count check. Added unit tests & refactored method names to give unit of time
> Ramp time defect

- agent/apiharness/src/main/java/com/intuit/tank/runner/TestPlanRunner.java
> SRE-19391 Implement StopBehavior

- web/web_support/src/main/java/com/intuit/tank/util/FilterUtil.java
- web/web_ui/src/main/webapp/filters/index.xhtml
- web/web_ui/src/main/webapp/scripts/reapply-filters.xhtml
Add ID column to filter and filter groups
> SRE-19430 Add ID column to filter and filter groups

- web/web_ui/src/main/webapp/filters/createNewFilterGroup.xhtml
- web/web_ui/src/main/webapp/filters/index.xhtml
- web/web_ui/src/main/webapp/resources/css/screen.css
- web/web_ui/src/main/webapp/scripts/assignment-editor.xhtml
- web/web_ui/src/main/webapp/scripts/post-data-editor.xhtml
- web/web_ui/src/main/webapp/scripts/query-string-editor.xhtml
- web/web_ui/src/main/webapp/scripts/request-cookies-editor.xhtml
- web/web_ui/src/main/webapp/scripts/request-header-editor.xhtml
- web/web_ui/src/main/webapp/scripts/response-cookies-editor.xhtml
- web/web_ui/src/main/webapp/scripts/response-header-editor.xhtml
- web/web_ui/src/main/webapp/scripts/validation-editor.xhtml
Responsive Create Filter Group Data Table: - Make data table in CreateFilterGroup page responsive to avoid pages of white space issue
**Changes**
- Primary changes in createNewFilterGroup.xhtml 
- Name refactor
> Responsive Create Filter Group Data Table

- agent/agent_common/src/main/java/com/intuit/tank/http/TankHttpUtil.java
- agent/agent_common/src/test/java/com/intuit/tank/http/TankHttpUtilTest.java
Fix for empty and null url params in Tank debugger
> SRE-19573 Fix for empty and null url params

- web/web_ui/src/main/webapp/projects/variables.xhtml
Make variables key field editable
> SRE-19600 Make variables key field editable

- web/web_ui/src/main/webapp/filters/index.xhtml
- web/web_ui/src/main/webapp/scripts/reapply-filters.xhtml
Make filters table id and checkbox columns static size
> Sre 19627 Make filters table id and checkbox columns static size

- data_access/src/main/java/com/intuit/tank/dao/ScriptDao.java
- pom.xml
- web/web_support/src/main/java/com/intuit/tank/script/TankXmlUploadBean.java
- web/web_ui/src/main/webapp/scripts/index.xhtml
> Sre 19610 Tank upload bug

- api/pom.xml
- pom.xml
- rest/service/reporting/src/main/java/com/intuit/tank/service/impl/v1/report/SummaryReportRunner.java
- tank_common/src/test/java/com/intuit/tank/transform/scriptGenerator/ConverterUtilTest.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/IncreasingWorkLoad.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/AgentWatchdog.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/VMQueue.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/VMTrackerImpl.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/VmMessageProcessorImpl.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/CreateInstance.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/JobRequest.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/KillInstance.java
- web/web_support/src/main/java/com/intuit/tank/notification/NotificationRunner.java
Fix Xray recorder deprecations
> Xray deprecations

- script_processor/src/test/java/com/intuit/tank/script/util/ScriptFilterUtilTest.java
- tools/script_engine/src/main/java/com/intuit/tank/tools/script/LoggingOutputLogger.java
SRE-20692 Redact SSNs from log messages
> SRE-20692 Redact SSNs from log messages

- api/src/main/java/com/intuit/tank/vm/vmManager/JobRequestImpl.java
SRE-20766 Fix printing of HashSet
> SRE-20766 Fix printing of HashSet

- pom.xml
- web/web_support/src/main/java/com/intuit/tank/project/JobTreeTableBean.java
> Library Updates [CVE-2021-44228]

- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
- agent/http_client_3/src/main/java/com/intuit/tank/httpclient3/TankHttpClient3.java
- agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java
- agent/http_client_5/src/main/java/com/intuit/tank/httpclient5/TankHttpClient5.java
- pom.xml
SRE-20769 Fix MIME type error in Tank debugger
> SRE-20769 Fix MIME type error in Tank debugger

- web/web_ui/src/main/webapp/scripts/script-edit-view.xhtml
> [SRE-20818] define lazy as false for empty DataTables

- agent/apiharness/pom.xml
- pom.xml
- readme.md
- web/web_support/pom.xml
> [SRE-20820] Add nashorn to runtime dependencies

- web/web_support/src/main/java/com/intuit/tank/project/JobTreeTableBean.java
- web/web_ui/src/main/webapp/projects/addWorkloadToJobQueue.xhtml
Insufficient permissions validation message
> Sre 20021 - Insufficient permissions validation message

- web/web_ui/src/main/webapp/scripts/index.xhtml
Script page refreshing every 2 seconds.
> SRE-21147 Script page refreshing every 2 seconds.

- data_access/src/main/java/com/intuit/tank/dao/ScriptDao.java
- data_access/src/test/java/com/intuit/tank/dao/DaoTestUtil.java
- data_access/src/test/java/com/intuit/tank/dao/ScriptDaoTest.java
> SRE-21477 Fix reordering issue

- pom.xml
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/AgentWatchdog.java
- tank_vmManager/src/test/java/com/intuit/tank/vmManager/AgentWatchdogTest.java
- tank_vmManager/src/test/resources/log4j2.xml
> [SRE-20063] Update AgentWatchDog to replace instances when unable to connect

- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
> [SRE-22163] - Test Plan Bug

- doc/tank_installation_guide/pom.xml
- doc/tank_user_guide/pom.xml
- pom.xml
> override plugin repo with https endpoint

- docs-requirements.txt
- docs/.pages
- docs/apispec.md
- docs/openapi-spec.json
- mkdocs.yml
Introducing Swagger OpenAPI 3 Spec for Tank Web APIs
> SRE-23282:Swagger OpenAPI 3 Spec for Tank Web APIs

- agent/agent_common/src/main/java/com/intuit/tank/http/json/JsonResponse.java
- agent/agent_common/src/test/java/com/intuit/tank/http/json/JsonResponseTest.java
- agent/agent_common/src/test/resources/json-response.json
Remove `@` filter from response payload
- Update unit testing
> [SRE-23687] Remove `@` filter from response payload

- web/web_ui/src/main/webapp/projects/projectview.xhtml
title: Product field not visible or editable for Projects
On the Project page, added the Products pull-down
> [SRE-23932] On the Project page, added the Products pull-down

- web/web_support/src/main/java/com/intuit/tank/script/ScriptBean.java
Reverts intuit/Tank#211
I believe: This copying the contents of every script
> Revert "[SRE 23283] SaveAs Icon in table view creates empty Script"

- web/web_support/src/main/java/com/intuit/tank/script/ScriptBean.java
title: - Script save-as button copies script steps
> [SRE-24225] Script save-as button copies script steps

- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/TestPlanStarterTest.java
- current Threads
- target Threads
> [SRE-24384] Publish CloudWatchMetrics

- api/src/main/java/com/intuit/tank/storage/FileStorageFactory.java
- api/src/main/java/com/intuit/tank/storage/S3FileStorage.java
- api/src/test/java/com/intuit/tank/storage/FileStorageFactoryTest.java
- tools/script_filter/src/main/java/com/intuit/tank/tools/script/ConfiguredLanguage.java
- web/web_support/src/main/java/com/intuit/tank/project/DataFileBrowser.java
- web/web_ui/src/main/webapp/datafiles/index.xhtml
- web/web_ui/src/main/webapp/scripts/index.xhtml
> [SRE-24440] Fix DataFile Storage

- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
- web/web_support/src/main/java/com/intuit/tank/project/JobTreeTableBean.java
- web/web_support/src/test/java/com/intuit/tank/project/JobTreeTableBeanTest.java
- Fix currentThreads
- Add ActiveThreads
> [SRE-24553] Add activeThreads Metric

- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
> Fix: NullPointerException in active thread counting

- proxy-parent/proxy-extension/src/test/java/com/intuit/tank/proxy/ProxyAppTest.java
- proxy-parent/proxy-extension/src/test/java/com/intuit/tank/proxy/settings/ui/RuleEditorDialogTest.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java
- tank_vmManager/src/test/java/com/intuit/tank/perfManager/workLoads/JobManagerTest.java
> Job Manager ParallelStream

- pom.xml
- search/lucene_indexer/src/main/java/com/intuit/tank/search/lucene/LuceneService.java
- test_support/pom.xml
- web/web_support/src/main/java/com/intuit/tank/project/JobTreeTableBean.java
- web/web_ui/pom.xml
> library updates

- agent/apiharness/src/main/java/com/intuit/tank/harness/logging/LogEvent.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/logging/LogEventTest.java
title: - Obfuscate `pwd` and tickets by regex
> Obfuscate `pwd` and tickets by regex

- pom.xml
- rest/api/pom.xml
- rest/pom.xml
- web/web_support/src/main/java/com/intuit/tank/config/AdminFilter.java
- web/web_support/src/main/java/com/intuit/tank/config/LoginFilter.java
- web/web_support/src/main/java/com/intuit/tank/util/RestSecurityFilter.java
- web/web_ui/src/main/webapp/WEB-INF/web.xml
> web.xml -> Jersey annotations

- agent/apiharness/src/main/java/com/intuit/tank/harness/logging/LogEvent.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/MockResponse.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/logging/LogEventTest.java
Security: - Obfuscate tickets by regex in header
> SRE-25928 : Obfuscate tickets by regex in header

- agent/apiharness/src/main/java/com/intuit/tank/harness/logging/LogEvent.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/logging/LogEventTest.java
title: - Obfuscate SSN and DOB by regex
JIRAs:
- https://jira.intuit.com/browse/SRE-27053
- https://jira.intuit.com/browse/SRE-27052
> Obfuscate SSN and DOB

- agent/http_client_3/src/test/java/com/intuit/tank/httpclient3/TankHttpClient3Test.java
- agent/http_client_4/src/test/java/com/intuit/tank/httpclient4/TankHttpClient4Test.java
- agent/http_client_5/src/test/java/com/intuit/tank/httpclient5/TankHttpClient5Test.java
**TankHttpClientTest Fix - commenting out until fixed**
> Commenting out TankHttpClientTest until fixed

- tank_vmManager/src/main/java/com/intuit/tank/vmManager/VMTrackerImpl.java
> Catch SQL Query Traces for CloudStatus calls which return HttpStatus Code 204

- agent/apiharness/src/test/java/com/intuit/tank/harness/APITestHarnessTest.java
- buildspec.yml
- pom.xml
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/IncreasingWorkLoad.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java
- web/web_ui/pom.xml
> AWS X-Ray SDK Instrumentation

- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/IEnvironmentInstance.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonDataConverter.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
- tank_vmManager/src/test/java/com/intuit/tank/vmManager/environment/amazon/AmazonDataConverterTest.java
- Remved `tagInstance` method (after creation)
- Added `tagSpecifications` to runInstancesRequestTemplate to tag during build time
- Change DataConverter to `static` methods
- Updated DataConverter Tests
> Tag Agents at Creation Time

- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
We don't use or need the async capability in the amazon ec2 instance connector. Reducing this to a simple blocking connector for simplification. 
> Async -> Blocking requester in AmazonInstance

- harness_data/src/main/java/com/intuit/tank/harness/data/HDTestPlan.java
- tank_common/src/main/java/com/intuit/tank/transform/scriptGenerator/ConverterUtil.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/IncreasingWorkLoad.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
> Parallel EC2 request by regions

- agent/apiharness/pom.xml
- agent/apiharness_pkg/pom.xml
- buildspec.yml
- pom.xml
- tools/agent_debugger_pkg/pom.xml
> Add missing nashorn dependency

- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/AgentRunData.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/APITestHarnessTest.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/AgentRunDataTest.java
- rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/util/JobDetailFormatter.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/WorkLoadFactory.java
- web/web_support/src/main/java/com/intuit/tank/job/ActJobNodeBean.java
- web/web_support/src/main/java/com/intuit/tank/project/JobDetailFormatter.java
- web/web_ui/src/main/webapp/agents/index.xhtml
- web/web_ui/src/main/webapp/projects/projectjobqueue.xhtml
**Nonlinear Workload - Simplify Code + QOL changes**
Small update to nonlinear workload including:
- **simplifying and cleaning up the code**: since agents are now sent ramp rates between 0-1 user/sec, they is no longer a need for ramp rate delay logic, a function to configure agent orchestration (`configureNonlinearAgentRunData()`) and any other code related to the previous staggered start logic for agents. Now all agents run their own nonlinear ramp and only require a target ramp rate to do so
- **QOL UI changes**: replaced user ramp rate with estimated steady state users in agent tracker and limited decimal ramp rate values to 2 decimal places
- **Added agent thread counter to help with debugging agent threads** (i.e AGENT-1, AGENT-2, etc)
Please make sure these check boxes are checked …
> Nonlinear Workload - Simplify Code + QOL changes 

- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
**Loop through list of Subnet IDs in AmazonInstance**
Small update to reset pointer to start of list to loop through subnetIds and divide instances between subnets
> Loop through list of Subnet IDs in AmazonInstance

- api/src/main/java/com/intuit/tank/vm/settings/VmManagerConfig.java
- web/web_support/src/main/java/com/intuit/tank/config/LoginFilter.java
**Update to use existing entry in settings file**
> Tank API Token Authentication: Update to use existing entry in settings file

- agent/agent_common/src/main/java/com/intuit/tank/http/BaseRequest.java
- agent/agent_common/src/test/java/com/intuit/tank/http/BaseRequestTest.java
- agent/http_client_3/src/main/java/com/intuit/tank/httpclient3/TankHttpClient3.java
- agent/http_client_3/src/test/java/com/intuit/tank/httpclient3/TankHttpClient3Test.java
- agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java
- agent/http_client_4/src/test/java/com/intuit/tank/httpclient4/TankHttpClient4Test.java
- agent/http_client_5/src/main/java/com/intuit/tank/httpclient5/TankHttpClient5.java
- agent/http_client_5/src/test/java/com/intuit/tank/httpclient5/TankHttpClient5Test.java
> Reset Content-Type after StringEntity

- web/web_ui/src/main/webapp/admin/index.xhtml
- web/web_ui/src/main/webapp/admin/logs.xhtml
- web/web_ui/src/main/webapp/admin/users.xhtml
- web/web_ui/src/main/webapp/filters/index.xhtml
- web/web_ui/src/main/webapp/projects/index.xhtml
- web/web_ui/src/main/webapp/scripts/index.xhtml
```
WARNING [http-nio-8080-exec-61] com.sun.faces.facelets.tag.faces.core.MetadataHandler.apply JSF1103: The metadata facet must be a direct child of the view in viewId /scripts/index.xhtml
```
> Resolve high volume warning message from jsf

- agent/agent_common/src/main/java/com/intuit/tank/http/BaseResponse.java
- agent/agent_standalone_pkg/src/main/assembly/assembly.xml
- agent/agent_standalone_pkg/src/main/assembly/zip-assembly.xml
- agent/agent_startup_pkg/src/main/assembly/assembly.xml
- agent/agent_startup_pkg/src/main/assembly/zip-assembly.xml
- agent/apiharness/src/main/java/com/intuit/tank/runner/method/LogicRunner.java
- agent/apiharness_pkg/src/main/assembly/assembly.xml
- agent/apiharness_pkg/src/main/assembly/zip-assembly.xml
- pom.xml
- tools/agent_debugger_pkg/pom.xml
- tools/agent_debugger_pkg/src/main/assembly/assembly.xml
- tools/script_filter/src/main/java/com/intuit/tank/tools/script/ConfiguredLanguage.java
- tools/script_filter/src/main/java/com/intuit/tank/tools/script/ScriptFilterRunner.java
- tools/script_filter_pkg/pom.xml
- tools/script_filter_pkg/src/main/assembly/assembly.xml
- web/web_support/src/main/java/com/intuit/tank/project/DataFileBrowser.java
In order to discover module services like scriptEngineFactories.
- JavaScript
- Groovy
- Ruby
> Update Assembly and Shade Plugin Transformers

- agent/http_client_3/src/main/java/com/intuit/tank/httpclient3/TankHttpClient3.java
- agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java
- agent/http_client_5/src/main/java/com/intuit/tank/httpclient5/TankHttpClient5.java
> Disable log message creation when not debugging

- api/pom.xml
- api/src/main/java/com/intuit/tank/harness/AmazonUtil.java
- api/src/test/java/com/intuit/tank/harness/AmazonUtilTest.java
mock AmazonUtilTest to save 30sec on build time
> mock AmazonUtilTest to save 30sec on build time

- api/src/main/java/com/intuit/tank/harness/AmazonUtil.java
- api/src/test/java/com/intuit/tank/harness/AmazonUtilTest.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
> IMDSv2 Required

- agent/agent_standalone/src/main/java/com/intuit/tank/standalone/agent/CommandListener.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/parsers/WorkloadParser.java
- api/src/test/java/com/intuit/tank/harness/AmazonUtilTest.java
- proxy-parent/WebConversation/src/main/java/com/intuit/tank/util/WebConversationJaxbParseXML.java
- rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/util/ScriptServiceUtil.java
- script_processor/src/main/java/com/intuit/tank/script/util/ScriptServiceUtil.java
- tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/JaxbUtil.java
- tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/PanelBuilder.java
- tools/script_filter/src/main/java/com/intuit/tank/tools/script/ScriptFilterRunner.java
- web/web_support/src/main/java/com/intuit/tank/script/ScriptCreationBean.java
> [SRE-30912] Disallow Doctype Declaration

- rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/services/projects/ProjectServiceV2Impl.java
**Tank V2 API: Add Null Checks Before Assignments for Create/Update Projects**
Allows users to create/update projects without having to pass values for each entry of the payload
> Tank V2 API: Add Null Checks Before Assignments for Create/Update Projects

- api/src/main/java/com/intuit/tank/jobs/models/CreateJobRegion.java
- api/src/main/java/com/intuit/tank/jobs/models/CreateJobRequest.java
- rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/JobController.java
- rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/services/jobs/JobServiceV2Impl.java
**Nonlinear Workload - Update POST /jobs endpoint for nonlinear changes**
- Now that nonlinear job configuration has been finalized (https://github.com/intuit/Tank/pull/320), update endpoint to accept new nonlinear job parameters
> Nonlinear Workload - Update POST /jobs endpoint for nonlinear changes

- agent/agent_startup/src/main/java/com/intuit/tank/agent/AgentStartup.java
> Updating Agent Startup Command

- web/web_ui/src/main/webapp/projects/projectview.xhtml
**Fix: Cancel button now working when canceling Script Group deletion**
JIRA: https://jira.intuit.com/browse/SRE-32632
> Fix: Cancel button now working when canceling Script Group deletion

- agent/apiharness/src/main/java/com/intuit/tank/harness/APIMonitor.java
> Single instance object mapper shared for the life of the APIMonitor

- web/web_support/src/main/java/com/intuit/tank/ProjectBean.java
- web/web_support/src/main/java/com/intuit/tank/project/UsersAndTimes.java
- web/web_ui/src/main/webapp/META-INF/context.xml
title: Project SaveAs now correctly copies all project values
> Project SaveAs now correctly copies all project values

- agent/agent_startup/src/main/java/com/intuit/tank/agent/AgentStartup.java
- agent/agent_startup_pkg/tank_agent/startAgent.sh
> Update AgentStartup command to pass in list of arguments

- agent/agent_startup_pkg/tank_agent/startAgent.sh
> Updating Command

- pom.xml
- support latest instance types
> Update AWS bom

- proxy-parent/owasp-proxy/pom.xml
- proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/http/dao/JdbcMessageDAO.java
- proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/util/BouncyCastleCertificateUtils.java
- Update bouncy castle `1.47` -> `1.79`
- Update spring-jdbc `2.5.6` -> `6.2.0`
[Security alert](https://github.com/intuit/Tank/security/dependabot/69)
> CVE-2024-38827

- agent/apiharness/src/main/java/com/intuit/tank/runner/method/RequestRunner.java
**Remove Response Body Regex Check**
This removes an unnecessary regex search on the response body of every response for any instance of Tank variables i.e #{sample_var}, thus saving a significant amount of computational time, memory, etc on each agent
> Remove Response Body Regex Check

- data_model/pom.xml
- pom.xml
- web/web_support/pom.xml
> pom updates

- agent/agent_common/pom.xml
- agent/agent_common/src/main/java/com/intuit/tank/http/TankHttpUtil.java
- pom.xml
- web/web_ui/pom.xml
- web/web_ui/src/main/webapp/WEB-INF/web.xml
- Update web.xml to identify uploader to use `native`
- Remove `commons.fileupload` dependency
> Use native Servlet 3.0 File Uploader

- tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/ActionProducer.java
> Fix AgentDebugger Typo

- data_access/src/test/resources/META-INF/persistence.xml
- pom.xml
- web/web_support/src/test/resources/META-INF/persistence.xml
Update H2 to resolve multiple security issues on the in memory unit tests for Tank. Disabled new H2 keywords to resolve build issues (`USER`, `END`, and `VALUE`).
> h2 2.0 migration

- pom.xml
- script_processor/pom.xml
- web/web_support/pom.xml
- web/web_ui/src/main/webapp/admin/users.xhtml
- web/web_ui/src/main/webapp/datafiles/index.xhtml
- web/web_ui/src/main/webapp/projects/projectview.xhtml
- web/web_ui/src/main/webapp/scripts/script-edit-view.xhtml
> Primefaces 14

- web/web_ui/src/main/webapp/filters/index.xhtml
**Fixes Filters Page After PrimeFaces Upgrade**
> Fixes Filters Page After PrimeFaces Upgrade

- agent/apiharness/src/main/java/com/intuit/tank/runner/method/RequestRunner.java
> Revert "Remove Response Body Regex Check"

- agent/apiharness/src/main/java/com/intuit/tank/runner/method/RequestRunner.java
Reverts intuit/Tank#375 
The Regex check was not the cause of the issue, it was the specific script
> Revert "Revert "Remove Response Body Regex Check""

- web/web_support/src/main/java/com/intuit/tank/auth/TankAuthenticator.java
- web/web_support/src/main/java/com/intuit/tank/auth/TankIdentityStore.java
- web/web_support/src/main/java/com/intuit/tank/auth/TankSecurityContext.java
- web/web_ui/src/main/webapp/WEB-INF/faces-config.xml
- web/web_ui/src/main/webapp/login.xhtml
Only affects username/password login flow
-----
> Restore JSF Routing to the Login Flow

- web/web_support/src/main/java/com/intuit/tank/auth/TankIdentityStore.java
- web/web_support/src/main/java/com/intuit/tank/config/LoginFilter.java
- web/web_support/src/main/java/com/intuit/tank/util/RestSecurityFilter.java
- web/web_support/src/test/java/com/intuit/tank/config/LoginFilterTest.java
- web/web_ui/src/main/webapp/WEB-INF/faces-config.xml
> Fix Authentication in LoginFilter

- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
- tank_vmManager/src/test/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstanceTest.java
- Unwrap CompletionException in exceptionally
- Narrow instance type retry to the errorCode `InsufficientInstanceCapacity`
> InsufficientInstanceCapacity Fix

- proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/util/BouncyCastleCertificateUtils.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/EmbeddedProxy.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/ProxyApp.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/config/CommonsProxyConfiguration.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/config/FixedProxyConfiguration.java
- proxy-parent/proxy-extension/src/main/java/com/intuit/tank/proxy/config/ProxyConfiguration.java
> Fix BouncyCastle Proxy Usage

- agent/apiharness/src/main/java/com/intuit/tank/harness/CommandListener.java
- rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/AgentController.java
- rest-mvc/impl/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/AgentControllerTest.java
> Return 202 when applicable

- web/web_support/src/main/java/com/intuit/tank/ProjectDescriptionBean.java
- web/web_ui/src/main/webapp/projects/index.xhtml
> banner in primfaces:messages

- agent/apiharness/src/main/java/com/intuit/tank/harness/test/data/Variables.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/functions/JexlMonetaryFunctionsTest.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/functions/JexlNumericFunctionsTest.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/functions/JexlStringFunctionsTest.java
- agent/apiharness/src/test/java/com/intuit/tank/harness/test/data/VariablesTest.java
- pom.xml
- Library Updates
- JexlPermissions whitelisting
- Unit Test Assertion CleanUp
> JEXL3 Updates

- agent/agent_common/pom.xml
- agent/agent_standalone/pom.xml
- agent/agent_standalone_pkg/pom.xml
- agent/agent_startup/pom.xml
- agent/agent_startup_pkg/pom.xml
- agent/http_client_3/pom.xml
- agent/http_client_4/pom.xml
- agent/http_client_jdk/pom.xml
- doc/pom.xml
- doc/tank_installation_guide/pom.xml
- doc/tank_user_guide/pom.xml
- harness_data/pom.xml
- jacoco-report-aggregator/pom.xml
- pom.xml
- proxy-parent/WebConversation/pom.xml
- proxy-parent/proxy-extension/pom.xml
- rest-mvc/pom.xml
- search/document_util/pom.xml
- search/lucene_indexer/pom.xml
- search/script_search/pom.xml
- test_support/src/main/resources/checkstyle.xml
- tools/agent_debugger/pom.xml
- tools/script_filter/pom.xml
- Update checkstyle version
- Update checkstyle configuration file
- Update static version to project.version in `jacoco-report-aggregator`
- Consistent xml boilerplate
> Check Style Cleanup

- api/src/test/java/com/intuit/tank/vm/vmManager/models/UserDetailTest.java
- data_model/src/test/java/com/intuit/tank/project/BaseJobTest.java
- data_model/src/test/java/com/intuit/tank/project/ScriptContainerTest.java
- data_model/src/test/java/com/intuit/tank/project/ScriptFilterTest.java
- data_model/src/test/java/com/intuit/tank/project/ScriptGroupStepTest.java
- data_model/src/test/java/com/intuit/tank/project/ScriptGroupTest.java
- data_model/src/test/java/com/intuit/tank/project/ScriptTest.java
- data_model/src/test/java/com/intuit/tank/project/TestPlanTest.java
- data_model/src/test/java/com/intuit/tank/project/WorkloadTest.java
- tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/ActionProducer.java
> Deprecated `Integer(int)`

- pom.xml
> dependency versions

- agent/apiharness/src/main/java/com/intuit/tank/harness/AgentUtil.java
- buildspec.yml
- pom.xml
- readme.md
- rest-mvc/impl/pom.xml
- rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/errors/GenericExceptionHandler.java
- web/web_support/src/test/java/com/intuit/tank/script/LogicStepEditorTest.java
- Simplify dependencies
- Add Exception handler for `NoResourceFoundException`
> Build with Java 25

- agent/agent_standalone/src/main/assembly/assembly.xml
- agent/agent_standalone/src/main/java/com/intuit/tank/standalone/agent/StandaloneAgentStartup.java
- agent/agent_startup/src/main/assembly/assembly.xml
- agent/agent_startup/src/main/java/com/intuit/tank/agent/AgentStartup.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java
- agent/apiharness/src/main/java/com/intuit/tank/harness/AgentRunData.java
- api/pom.xml
- api/src/main/java/com/intuit/tank/harness/AmazonUtil.java
- api/src/main/java/com/intuit/tank/storage/FileSystemFileStorage.java
- api/src/main/java/com/intuit/tank/storage/S3FileStorage.java
- api/src/main/java/com/intuit/tank/vm/settings/TankConfig.java
- pom.xml
- proxy-parent/owasp-proxy/pom.xml
- proxy-parent/proxy_pkg/src/main/assembly/assembly.xml
- proxy-parent/proxy_pkg/src/main/assembly/zip-assembly.xml
- reporting/db/src/main/java/com/intuit/tank/reporting/db/DatabaseResultsReporter.java
- rest-mvc/clients/pom.xml
- rest-mvc/clients/src/main/java/com/intuit/tank/clients/BaseClient.java
- rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/cloud/JobEventListener.java
- rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/services/agent/AgentServiceV2Impl.java
- tank_common/src/main/java/com/intuit/tank/transform/scriptGenerator/ConverterUtil.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/IncreasingWorkLoad.java
- tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/AgentWatchdog.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/VMTrackerImpl.java
- tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/JobRequest.java
- tools/agent_debugger_pkg/pom.xml
- web/web_support/src/test/java/com/intuit/tank/script/LogicStepEditorTest.java
- Remove `guava` dependencies
- Update dependencies
> Reduce final war file by 13MB (5%)
