all-in-one.sh
* Refactored creation of `start.sh`, `stop.sh`, `agent-standalone/run.sh'
to use heredocs in favor of `echo`. Easier to read and maintain.
* Cleaning up redirect syntax.
=> #79: Add path creation for `agent-standalone/run.sh`

data_access/src/main/java/com/intuit/tank/dao/ScriptDao.java, data_access/src/test/java/com/intuit/tank/dao/ScriptDaoTest.java, data_model/src/main/java/com/intuit/tank/project/Script.java, data_model/src/main/java/com/intuit/tank/project/SerializedScriptStep.java, data_model/src/test/java/com/intuit/tank/project/ScriptTest.java
Add compression to longBlob storage in RDS:
This really resolves (2) major issues:
- Every save to a script, including updates, created a new insert of the script.  The old one was abandoned and unreferenced. This causes excessive RDS disk space growth.
- Each script stored in the database has been a very large serialized list of steps. Passing the byte stream through the gzip stream compressor has reduced the storage size on the longBlobl storage space by +80%.
=> Add compression to longBlob storage in RDS

agent/apiharness/src/main/java/com/intuit/tank/harness/logging/LogEvent.java, agent/apiharness/src/test/java/com/intuit/tank/harness/logging/LogEventTest.java
Obfuscate password: - UserVariables Credentials exposed  in LogEvents
=> Obfuscate password in LogEvents

proxy-parent/proxy-extension/pom.xml, proxy-parent/proxy-extension/src/main/java/com/intuit/tank/entity/Application.java, proxy-parent/proxy-extension/src/test/java/com/intuit/tank/entity/ApplicationTest.java
Process 302 Transactions within the Proxy Recorder: - Be able to handle 302 HTTP Transactions within setResponseForCurrentTransaction method
=> Proxy Recorder: Process 302 Transactions

proxy-parent/proxy-extension/src/main/java/com/intuit/tank/entity/Application.java, proxy-parent/proxy-extension/src/main/java/com/intuit/tank/handler/BufferingHttpRequestHandler.java, proxy-parent/proxy-extension/src/test/java/com/intuit/tank/entity/ApplicationTest.java
**Redirect Proxy Mislabeled**: 
- Redirect Map cached old redirect information causing mislabeling in the proxy recorder
- Remove unnecessary Buffered request parameter
=> Remove redirect map caching old redirect data

web/web_ui/src/main/webapp/filters/index.xhtml, web/web_ui/src/main/webapp/scripts/reapply-filters.xhtml
Responsive Filter Page for Filter Group & Filter Table: - Data tables in Filters page that show filter groups & filters have static table size and does NOT support dynamic sizing 
=> Responsive Filter Page for Filter Group & Filter Table

data_access/src/main/java/com/intuit/tank/dao/ScriptDao.java, tank_common/src/main/java/com/intuit/tank/common/ScriptUtil.java
=> SRE-20512 Fix thinktime script apply

web/web_support/src/main/java/com/intuit/tank/project/WorkloadScripts.java, web/web_ui/src/main/webapp/projects/workloadScripts.xhtml
Fix ordering of script group insert
=> [SRE-22160] Fix ordering of script group insert

proxy-parent/owasp-proxy/pom.xml, proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/http/HttpConstants.java, proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/http/MessageUtils.java, proxy-parent/owasp-proxy/src/main/java/org/owasp/proxy/ssl/DefaultClientContextSelector.java, proxy-parent/proxy-extension/src/main/java/com/intuit/tank/entity/Application.java
Brotli encoding support in proxy
=> [SRE -23218] Brotli encoding support in proxy

web/web_support/src/main/java/com/intuit/tank/script/ScriptBean.java
title: SaveAs Icon in table view creates empty Script
The ScriptBean was not populating the script steps. When a script was copied ('save as'), these steps were not being copied over to the new script.
=> [SRE 23283] SaveAs Icon in table view creates empty Script

agent/agent_common/src/test/java/com/intuit/tank/http/json/PlainTextRequestTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/APIMonitorTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/APITestHarnessTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/CommandListenerTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/TPSMonitorTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/functions/DataTypeFunctionsTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/functions/DateFunctionsTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/functions/JexlStringFunctionsTest.java, agent/apiharness/src/test/java/com/intuit/tank/harness/functions/StringFunctionsTest.java, agent/apiharness/src/test/java/com/intuit/tank/runner/TestPlanRunnerTest.java, agent/apiharness/src/test/java/com/intuit/tank/runner/method/RequestRunnerTest.java, agent/apiharness/src/test/java/com/intuit/tank/runner/method/RunnerFactoryTest.java, api/src/test/java/com/intuit/tank/vm/settings/ModifiedEntityMessageTest.java, api/src/test/java/com/intuit/tank/vm/settings/OidcSsoConfigTest.java, api/src/test/java/com/intuit/tank/vm/settings/ReportingConfigTest.java, api/src/test/java/com/intuit/tank/vm/vmManager/JobRequestImplCpTest.java, api/src/test/java/com/intuit/tank/vm/vmManager/VMInstanceRequestTest.java, api/src/test/java/com/intuit/tank/vm/vmManager/VMJobRequestTest.java
title: - Test variable scope changed to private across new tests + fixed a test exiting when ran in IDE (code cov unchanged) 
=> Code Coverage Follow up: Updating test variable scope to private 

rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/AgentController.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/DataFileController.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/JobController.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/ProjectController.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/ScriptController.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/errors/GenericExceptionHandler.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/jobs/CreateJobRequest.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/agent/AgentServiceV2.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/agent/AgentServiceV2Impl.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/datafiles/DataFileServiceV2.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/datafiles/DataFileServiceV2Impl.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/jobs/JobServiceV2.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/jobs/JobServiceV2Impl.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/projects/ProjectServiceV2.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/projects/ProjectServiceV2Impl.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/scripts/ScriptServiceV2.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/scripts/ScriptServiceV2Impl.java, rest-mvc/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/AgentControllerTest.java, rest-mvc/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/DataFileControllerTest.java, rest-mvc/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/JobControllerTest.java, rest-mvc/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/ProjectControllerTest.java, rest-mvc/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/ScriptControllerTest.java
This PR includes the following changes to prepare for merging V2 clients:
- Created `/names` endpoint for project, datafile, scripts that returns < id, names> list for each service
- Added new routes to agent and projects used by V2 client dependencies (agent, tools)
- Fixed an issue with uploading compressed datafile in QA, now decompresses the file correctly
- Updated job/agent instance status response to return a status string instead of no content
- Added new job creation naming options and a default job name if naming parameters are left blank
- Hid non-user-facing agent routes from Swagger UI (i.e `v2/agent/ready`, etc)
- Repository owners will merge your PR …
=> Added new routes for clients and fixed datafile compression issue

tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java
- Fix response.uri() `null` in retry logic
- Catch `NoRouteToHostException` and simplify logging
=> NoRouteToHostException

web/web_support/src/main/java/com/intuit/tank/job/ActJobNodeBean.java, web/web_support/src/main/java/com/intuit/tank/job/JobNodeBean.java, web/web_support/src/main/java/com/intuit/tank/job/ProjectNodeBean.java, web/web_support/src/main/java/com/intuit/tank/job/VMNodeBean.java, web/web_ui/src/main/webapp/agents/index.xhtml, web/web_ui/src/main/webapp/projects/projectjobqueue.xhtml
**Update Agent Tracker UI to display currently running jobs and agents**
The Agent Tracker UI has been updated with the following changes:
- At the project level, the status of running jobs (i.e 4/5 Jobs Running)
- At the job level, the status of running agents (8/10 Agents Running) 
**Notes**:
- The total amount of jobs/agents corresponds to the total subnodes of jobs and agents that are not terminated
- Filtering to include finished jobs will not change the total running jobs in the UI
- Terminating an agent will drop the total running agents by one
**Screenshots**: 
All jobs and agents running: 
Ramp Paused - 2 Agents Running
Job Stopped - 0 Agents Running
Job recently completed + filtering to include finished jobs
Project Completed (All jobs completed) 
New jobs created for the …
=> [SRE-26712] Update Agent Tracker UI to display currently running jobs and agents

tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java, tank_vmManager/src/main/java/com/intuit/tank/vmManager/AgentWatchdog.java, tank_vmManager/src/test/java/com/intuit/tank/vmManager/AgentWatchdogTest.java
**Short-term fix for agents stuck in pending**
As part of this [RCA Action Item](https://jira.intuit.com/browse/SRE-27028), a small temporary fix in the agent retry logic has been implemented and tested in QA-Tank.
Agents in `pending` status will no longer be relaunched by the agent retry logic. These agents have already reported back to the controller and wait for a start command from the controller while in `pending` status. They will no longer be terminated if the process from agent initialization to receiving this start command takes more than three minutes. Instead, agents that are still stuck in `starting` status and have not reported back to the controller will be relaunched. 
This is a short-term solution that has been validated to be working in QA-Tank, and will eventually be …
=> [SRE-27144] Short-term fix for agents stuck in pending

rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/agent/Namespace.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/datafiles/Namespace.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/filters/Namespace.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/jobs/Namespace.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/projects/Namespace.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/projects/adapter/Namespace.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/models/scripts/Namespace.java
title: - Reverting XML namespaces from V2 back to V1
Tank tools currently running the V1 API are expecting NAMESPACE_V1 from Tank XML files, while the namespace for several models has been updated to V2. To remediate this issue, it will need to be reverted back to V1 to work with the current V1 tools. It will be kept at V1 since a namespace version update is not needed for continued functionality. 
=> Reverting XML namespaces from V2 back to V1

rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/filters/FilterServiceV2Impl.java, rest-mvc/src/main/resources/application.yml, web/web_ui/src/main/webapp/projects/projectview.xhtml
**Script Group AJAX Fix- set component to not load dynamically**
The intial fix for the script group dialogue component issue, where ajax calls are reloading cached Javascript files and stalling the page. Setting the component to not load dynamically will ensure all components are loaded beforehand to successfully complete the AJAX calls. This fix will only affect that specific component. 
=> Script Group AJAX Fix- set component to not load dynamically

web/web_support/src/main/java/com/intuit/tank/ProjectDescriptionBean.java, web/web_support/src/main/java/com/intuit/tank/auth/TankAuthenticator.java, web/web_support/src/main/java/com/intuit/tank/converter/ScriptConverter.java, web/web_support/src/main/java/com/intuit/tank/filter/FilterGroupCreationBean.java, web/web_support/src/main/java/com/intuit/tank/project/DataFileBrowser.java, web/web_support/src/main/java/com/intuit/tank/project/JobTreeTableBean.java, web/web_support/src/main/java/com/intuit/tank/project/WorkloadScripts.java, web/web_support/src/main/java/com/intuit/tank/script/ScriptBean.java, web/web_support/src/main/resources/log4j2.xml, web/web_ui/src/main/webapp/agents/index.xhtml, web/web_ui/src/main/webapp/datafiles/index.xhtml, web/web_ui/src/main/webapp/filters/index.xhtml, web/web_ui/src/main/webapp/projects/index.xhtml, web/web_ui/src/main/webapp/projects/projectview.xhtml, web/web_ui/src/main/webapp/scripts/index.xhtml
title: - **Temporary AJAX fix - disable ajax for affected calls + remove V2 banner** 
Temporary fix for PF AJAX issue by disabling the AJAX request call altogether for the two affected calls - Add Script and Delete Script from the script group. The V2 client banner is also being removed to avoid any interference with the UI. Added backend logging to debug while investigating the root cause. 
=> Temporary AJAX fix - disable ajax for affected calls + remove V2 client banner 

rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/ScriptController.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/scripts/ScriptServiceV2.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/scripts/ScriptServiceV2Impl.java, rest-mvc/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/ScriptControllerTest.java
**Tank API V2: Add script update endpoint to import Tank XML scripts**
`/v2/scripts/update`
This endpoint mirrors the functionality of importing Tank XML scripts to update existing scripts. It supports both XML and `.gzip` files. 
=> Tank V2 API: Add script update endpoint to import Tank XML scripts

agent/http_client_3/pom.xml, agent/http_client_3/src/test/java/com/intuit/tank/httpclient3/TankHttpClient3Test.java, agent/http_client_3/src/test/resources/mappings/httpbin.org-stubs.json, agent/http_client_4/pom.xml, agent/http_client_4/src/test/java/com/intuit/tank/httpclient4/TankHttpClient4Test.java, agent/http_client_4/src/test/resources/mappings/httpbin.org-stubs.json, agent/http_client_5/pom.xml, agent/http_client_5/src/test/java/com/intuit/tank/httpclient5/TankHttpClient5Test.java, agent/http_client_5/src/test/resources/mappings/httpbin.org-stubs.json, pom.xml
**Updated TankHttpClientTests to use mock server (WireMock)**
Updated tests to make calls to a mock server instead of [httpbin.org](httpbin.org), eliminating the need to connect and depend on it during test runs (which has resulted in a lot of inconsistent test failures). Instead, it makes use of [ WireMock](https://wiremock.org/) for its mock server, alongside the mock API sample ([httpbin.org-stubs.json](https://github.com/intuit/Tank/pull/258/files#diff-9a6d54b161ed3d4f02e25edcf94bd88f36c3bd0e593d9ce387548bd7409e0263)) for httpbin.org itself. This creates a mock API server that simulates the behavior and responses of httpbin.org with no changes to what is being tested. 
This also cuts down the total average test time duration from several minutes to 3-4 seconds. 
Please make sure these …
=> Updated TankHttpClientTests to use mock local server (WireMock)

web/web_support/src/main/java/com/intuit/tank/project/WorkloadScripts.java
**Script Groups: Add Selected scripts to script list in correct order**
This PR fixes a bug where under Script Groups, Selected scripts are being added to the list of project scripts in inverse order such that the last selected script becomes the first script added. This has been changed such that Selected scripts are added to the list of project scripts in the order they are selected. 
=> Script Groups: Add Selected scripts to script list in correct order

rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/clients/DataFileClient.java, tools/agent_debugger/src/main/java/com/intuit/tank/tools/debugger/AgentDebuggerFrame.java
**Tank Debugger: Accept large datafiles and process datafiles locally**
The Tank Debugger tool now accepts larger datafiles, as well as added logic to correctly process data files with scripts when running the tool locally
=> Tank Debugger: Accept large datafiles and process datafiles locally

data_model/src/main/java/com/intuit/tank/project/ScriptGroup.java, data_model/src/main/java/com/intuit/tank/project/ScriptGroupStep.java, web/web_support/src/main/java/com/intuit/tank/project/WorkloadScripts.java, web/web_ui/src/main/webapp/projects/projectview.xhtml
**Script Group - Enable script re-ordering in script groups**
This change allows users to reorder scripts in the script group list per script group via drag and drop. This change also fixes the issue of duplicate scripts being added back to available scripts by updating the `equals` function to check against both ID and script. 
=> Script Group - Enable script re-ordering in script groups

rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/datafiles/DataFileServiceV2Impl.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/services/scripts/ScriptServiceV2Impl.java
**Autoclose File Upload Resources with try-with-resources statement**
Updated resource management for file uploads (script/datafile uploads) to autoclose at the end of the statement to avoid any future memory leak issues
=> Autoclose File Upload Resources with try-with-resources statement

api/src/main/java/com/intuit/tank/harness/AmazonUtil.java
**Thread Buildup Fix - Reduce total active threads to only agent threads**
Currently, when running a job, each agent instance is spinning up numerous additional threads per user thread, resulting in a total of up to 10x-15x times the amount of active threads requested. This resulted in an overhead of unnecessary active threads during job runs, and in some cases, caused agents to crash for certain EC2 instance types when ran long enough:
The root cause of these unnecessary additional threads was found to be due to a call from the `LogUtil` class to `AmazonUtil` creating a new `HttpClient` object each time it was called and subsequently spinning up around 7-8 helper threads in the process for each call for each agent/user thread (see above). The logging util class is used throughout the …
=> Thread Buildup Fix - Reduce total active threads to only agent threads

data_model/src/main/java/com/intuit/tank/project/JobRegion.java
**Small fix for saving new linear project**
Sets a default value for nonlinear region percentages (similar to the new [numAgents](https://github.com/intuit/Tank/blob/cf7b7d817cc1f3ed0577b019edf309e19ce03457/data_model/src/main/java/com/intuit/tank/project/BaseJob.java#L72) field) to allow saving/save as for new linear projects that do not use nonlinear settings, passing the not-null check
=> Small fix for saving new linear project

data_access/src/main/java/com/intuit/tank/dao/BaseDao.java, data_access/src/main/java/com/intuit/tank/dao/ProjectDao.java, data_access/src/main/java/com/intuit/tank/dao/ScriptDao.java, data_access/src/main/java/com/intuit/tank/dao/VMImageDao.java, data_access/src/test/java/com/intuit/tank/dao/BaseDaoTest.java, data_access/src/test/java/com/intuit/tank/dao/DaoTestUtil.java, data_access/src/test/java/com/intuit/tank/dao/JobInstanceDaoTest.java, data_access/src/test/java/com/intuit/tank/dao/ProjectDaoTest.java, data_access/src/test/java/com/intuit/tank/dao/ScriptDaoTest.java, data_access/src/test/java/com/intuit/tank/dao/util/ProjectDaoUtilTest.java, data_model/src/main/java/com/intuit/tank/project/ScriptGroup.java, data_model/src/main/java/com/intuit/tank/project/Workload.java, data_model/src/test/java/com/intuit/tank/project/JobInstanceTest.java
=> Improve DataAccess Code Coverage 62% -> 78%

web/web_ui/src/main/webapp/projects/projectview.xhtml
**Nonlinear Workload - Remove 1.0 user/sec Ramp Rate Limit per Agent**
Updates UI to allow entry of ramp rates above 1.0 user/sec
=> Nonlinear Workload - Remove 1.0 user/sec Ramp Rate Limit per Agent

agent/apiharness/src/main/java/com/intuit/tank/harness/CommandListener.java
**Implement Retry for Agents Starting HttpServer**
The most common reason for agents not being able to connect to the controller and requiring a restart (terminating that instance and spinning up a new one) observed so far is its inability to start its HttpServer. The cause has been pinpointed: another service is running on that port, and the agent fails to connect and throws an error, causing it to terminate. This has now been fixed to retry the call to start the httpserver, saving time in which the agent will come up (on average 40-60 seconds delay compare to terminating and restarting (4+ mins). This issue rarely occurs per job run, but the likelihood increases as the number of agents started at once increases (most likely will run into this when running 100+ agents at once). This …
=> Implement Retry for Agents Starting HttpServer

api/src/main/java/com/intuit/tank/vm/vmManager/JobRequest.java, api/src/main/java/com/intuit/tank/vm/vmManager/JobRequestImpl.java, api/src/test/java/com/intuit/tank/vm/vmManager/JobRequestImplCpTest.java, data_model/src/main/java/com/intuit/tank/project/BaseJob.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/util/JobDetailFormatter.java, tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java, tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/WorkLoadFactory.java, web/web_support/src/main/java/com/intuit/tank/job/ActJobNodeBean.java, web/web_support/src/main/java/com/intuit/tank/job/JobNodeBean.java, web/web_support/src/main/java/com/intuit/tank/job/JobQueueAction.java, web/web_support/src/main/java/com/intuit/tank/project/JobDetailFormatter.java, web/web_support/src/main/java/com/intuit/tank/project/JobMaker.java, web/web_ui/src/main/webapp/agents/index.xhtml, web/web_ui/src/main/webapp/projects/addWorkloadToJobQueue.xhtml, web/web_ui/src/main/webapp/projects/projectjobqueue.xhtml
**Set Initializing Agents Before Load Start Configurable Per Job**
Added `Enable Two-Step Job Start` job option that will toggle the two-step process of initializing agents before start load (https://github.com/intuit/Tank/pull/294). 
This is set to `false` by default meaning new projects will create jobs that will run and start load as expected. 
=> Set Initializing Agents Before Load Start Configurable Per Job

tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java, tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/IEnvironmentInstance.java, tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
`findDNSName` was calling describeInstances on instances in the wrong region causing 400s.
These changes resolve that issue and cleanup up the other `describeInstances` usage in AmazonInstance.java
=> DescribeInstances Rewrite

agent/apiharness/pom.xml, agent/apiharness/src/main/java/com/intuit/tank/harness/APIMonitor.java, agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java, web/web_support/pom.xml
The APIHarness needs to do httpclient communication to the controller without the spring clients.
=> APIHarness changes to support java11

web/web_support/src/main/java/com/intuit/tank/auth/sso/TankOidcAuthorization.java
**Pull SSO client secret from SSM**
Adds option to store client secret in SSM to be pulled on SSO login - returns the default value for client secret key from `settings.xml` file if set to value not matching SSM key path (`/*`)
=> Pull SSO client secret from SSM

agent/agent_common/src/main/java/com/intuit/tank/http/BaseResponse.java, agent/agent_common/src/main/java/com/intuit/tank/http/TankHttpUtil.java, agent/agent_common/src/test/java/com/intuit/tank/http/BaseResponseTest.java, agent/agent_common/src/test/java/com/intuit/tank/http/TankHttpUtilTest.java, agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java, agent/apiharness/src/main/java/com/intuit/tank/runner/TestPlanRunner.java, agent/http_client_3/src/main/java/com/intuit/tank/httpclient3/TankHttpClient3.java, agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java, agent/http_client_5/src/main/java/com/intuit/tank/httpclient5/TankHttpClient5.java
Remove logResponse String builder during all http requests
This change only creates the response log message only if using with Agent Debugger Tool and if Log Level is set to `DEBUG` instead of creating it by default on each step - decreasing the memory allocated for the log message string per agent thread. It also now correctly logs error messages from `TestPlanStarter`, including catching OOM exceptions.
**BEFORE**
**AFTER**
=> [SRE-30501] Remove logResponse String builder during all http requests

agent/apiharness/src/main/java/com/intuit/tank/harness/APITestHarness.java, agent/apiharness/src/main/java/com/intuit/tank/harness/logging/ThreadLocalLogEvent.java, api/src/main/java/com/intuit/tank/harness/HostInfo.java
Agent debugger takes a very long time to prepare a script to run. The majority of that time is just setting up the logevent. The PR reduces that time. 
Best measure with the TEST `APITestHarnessTest.testRunConcurrentTestPlan()`
> before: 22 sec (46 sec on work network)
> after: 10 sec
=> focus logging eventLog creation on local usage

agent/apiharness/src/main/java/com/intuit/tank/runner/TestPlanRunner.java
**Fix Step StopBehavior to exit script at end of step**
This fixes a flaw in the Step StopBehavior logic where after being sent a stop command to a job configured with `Stop Behavior` : `Step`, the user would continue executing the remaining steps in the test plan instead of returning and exiting at the end of step. 
=> Fix Step StopBehavior to exit script at end of step

agent/apiharness/src/main/java/com/intuit/tank/harness/TestPlanStarter.java
**Fix Stop during Initial Ramp for Nonlinear Workload**
Simple fix for an issue where stopping a nonlinear job during the initial ramp (the duration of time until the ramp rate reaches the target ramp rate) will continue running the job due to the no checks for agent stop command - this results in the initial ramp ignoring the stop command and continuing to ramp up until target ramp rate is reached (enters main loop). It also resulted in unexpected behavior when stopping a paused job during the initial ramp - this exits the pause state and continues ramping up before entering the main loop and stopping. 
Adding the check for the agent stop command in the initial ramp method now stops the ramp as expected, whether the job is  running or paused. 
Please make sure these check boxes are …
=> Fix Stop during Initial Ramp for Nonlinear Workload

api/src/main/java/com/intuit/tank/vm/vmManager/JobRequest.java, api/src/main/java/com/intuit/tank/vm/vmManager/JobRequestImpl.java, api/src/main/java/com/intuit/tank/vm/vmManager/JobVmCalculator.java, data_model/src/main/java/com/intuit/tank/project/BaseJob.java, rest-mvc/src/main/java/com/intuit/tank/rest/mvc/rest/util/JobDetailFormatter.java, tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java, tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/WorkLoadFactory.java, web/web_support/src/main/java/com/intuit/tank/project/JobDetailFormatter.java, web/web_support/src/main/java/com/intuit/tank/project/JobMaker.java, web/web_ui/src/main/webapp/META-INF/context.xml, web/web_ui/src/main/webapp/projects/addWorkloadToJobQueue.xhtml, web/web_ui/src/main/webapp/projects/projectview.xhtml
**Nonlinear Workload - Automatically Calculate Number of Agents based on Total Ramp Rate and Max Users/Sec per Agent**
This change improves the user experience of setting up nonlinear workload jobs. Currently, the user inputs the ramp rate per agent and the number of agents they want for the job, which requires the person to work backward to find the total ramp rate. This change allows the user to set the total TPS (user/sec ramp) for the entire job, along with a max user/sec ramp rate per agent and lets the controller automatically calculate the number of agents needed for the job. This follows the same pattern as we have for linear jobs, where the user inputs the total users for the job and max users per agent.
** PR …
=> Nonlinear Workload - Calculate Number of Agents based on Total Ramp Rate and Max Users/Sec per Agent

agent/apiharness/src/main/java/com/intuit/tank/harness/logging/LogEvent.java, agent/http_client_3/src/main/java/com/intuit/tank/httpclient3/TankHttpClient3.java, agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java, agent/http_client_jdk/src/main/java/com/intuit/tank/httpclientjdk/TankHttpClientJDK.java
=> Simplify slow call logging events

agent/apiharness/src/main/java/com/intuit/tank/harness/APIMonitor.java
The placement of the `Thread.sleep` within the try-catch block instead of in a `finally` block of the APIMonitor `run()` method leads to a retry loop whenever any exception is thrown - resulting in an explosion of calls from the affected agent to the controller, spiking CPU and memory for both. This fixes this bug by moving the sleep to where it needs to be. 
=> [SRE-31553] Fix APIMonitor Retry Loop Bug

data_model/src/main/java/com/intuit/tank/project/BaseJob.java, web/web_ui/src/main/webapp/META-INF/context.xml
**Increase Decimal Precision of Max Users/Sec Per Agent**
Increases Decimal Precision for Max Users/Sec Per Agent from 2 to 4 decimal points to avoid any rounding issues for precise calculations - previously rounded up to 2 decimal points resulting in an extra agent
=> Increase Decimal Precision of Max Users/Sec Per Agent

tank_vmManager/src/main/java/com/intuit/tank/perfManager/workLoads/JobManager.java, tank_vmManager/src/main/java/com/intuit/tank/vmManager/environment/amazon/AmazonInstance.java
**Fix: Handle Controller Restarts**
When the Tank controller restarts, it maintains connectivity to its running agents via `findAgent()` which creates an `ec2client` per region to pull instance data. This allows the controller to pull each agent's instance URL to send agent commands (start, stop, pause, and kill). Previously, it only did this for a single region (`getConfiguredRegions()`) - the region the controller was in - resulting in failed calls to agents in other regions. This fixes this issue by looping through all available agent regions (`getRegions()`), and thus has no issue in connecting to any running agents after a controller restart. 
- Repository owners …
=> Fix: Handle Controller Restarts

agent/agent_standalone/src/main/java/com/intuit/tank/standalone/agent/StandaloneAgentStartup.java, agent/agent_startup/src/main/java/com/intuit/tank/agent/AgentStartup.java
Code that builds a command line by concatenating strings that have been entered by a user allows the user to execute malicious code.
Execute external commands using an array of strings rather than a single string. By using an array, many possible vulnerabilities in the formatting of the string are avoided.
In the following example, latlonCoords contains a string that has been entered by a user but not validated by the program. This allows the user to, for example, append an ampersand (&) followed by the command for a malicious program to the end of the string. The ampersand instructs Windows to execute another program. In the block marked 'BAD', latlonCoords is passed to exec as part of a concatenated string, which allows more than one command to be executed. However, in the block marked …
=> Building a command line with string concatenation

agent/agent_standalone/src/main/java/com/intuit/tank/standalone/agent/StandaloneAgentStartup.java, agent/agent_startup/src/main/java/com/intuit/tank/agent/AgentStartup.java, api/src/main/java/com/intuit/tank/storage/FileSystemFileStorage.java, data_access/src/main/java/com/intuit/tank/dao/DataFileDao.java
Extracting files from a malicious zip file, or similar type of archive, is at risk of directory traversal attacks if filenames from the archive are not properly validated.
Zip archives contain archive entries representing each file in the archive. These entries include a file path for the entry, but these file paths are not restricted and may contain unexpected special elements such as the directory traversal element (..). If these file paths are used to create a filesystem path, then a file operation may happen in an unexpected location. This can result in sensitive information being revealed or deleted, or an attacker being able to influence behavior by modifying unexpected files.
For example, if a zip file contains a file entry ..\sneaky-file, and the zip file is extracted to the …
=> Arbitrary file access during archive extraction ("Zip Slip")

agent/http_client_4/src/main/java/com/intuit/tank/httpclient4/TankHttpClient4.java
To avoid the client closing the connection pool prematurely
If the connection manager is shared its life-cycle is expected to be managed by the caller and it will not be shut down if the client is closed.
```
Connection pool shut down
```
=> Enable Connection Manager Sharing in Apache Http 4.5

agent/apiharness/src/main/java/com/intuit/tank/harness/logging/LogEvent.java, agent/apiharness/src/main/java/com/intuit/tank/runner/TestPlanRunner.java, agent/apiharness/src/test/java/com/intuit/tank/harness/logging/LogEventTest.java
Agent tracing has shown that `UUID.randomUUID` makes up 20% of the heap allocation during test runs. The LoveEvent.transactionID is being updated for every script step independent of usage. These code changes reduce the `UUID.randomUUID` call to the use cases in which the value is utilized.
=> Reduce calls to `UUID.randomUUID`

pom.xml
Follow up to https://github.com/intuit/Tank/pull/364, updates lucene version to 9.8.0 since the 10.0.0 library version requires java 21 instead of 17
=> Updating lucene version

agent/agent_common/pom.xml, agent/agent_common/src/main/java/com/intuit/tank/http/TankHttpUtil.java, api/src/main/java/com/intuit/tank/storage/S3FileStorage.java, pom.xml, rest-mvc/impl/pom.xml, rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/util/ScriptServiceUtil.java, script_processor/src/main/java/com/intuit/tank/script/util/ScriptServiceUtil.java, web/web_support/pom.xml
The apache library used to replace fileuploads is not packaged in Tank and only included when deployed with tomcat.
Thus commons.fileupload dependency is being restored and the tomcat dependency tags are moved directly in modules that are deployed in tomcat.
=> Restore commons.fileupload

rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/AgentController.java, rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/DataFileController.java, rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/JobController.java, rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/LogController.java, rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/ProjectController.java, rest-mvc/impl/src/main/java/com/intuit/tank/rest/mvc/rest/controllers/ScriptController.java, rest-mvc/impl/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/JobControllerTest.java, rest-mvc/impl/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/ProjectControllerTest.java, rest-mvc/impl/src/test/java/com/intuit/tank/rest/mvc/rest/controllers/ScriptControllerTest.java
- Ensure XML response are returned with an XML content-encoding header so they can be compressed at the reverse-proxy layer
- Simplify notFound responses
=> Fix content-type on /v2/jobs/script/{jobid}

web/web_support/src/main/java/com/intuit/tank/script/LogicStepEditor.java, web/web_support/src/main/java/com/intuit/tank/script/ScriptEditor.java, web/web_support/src/main/java/com/intuit/tank/script/ScriptRequestEditor.java, web/web_support/src/test/java/com/intuit/tank/script/LogicStepEditorTest.java, web/web_support/src/test/java/com/intuit/tank/script/ScriptEditorTest.java, web/web_support/src/test/java/com/intuit/tank/script/ScriptRequestEditorTest.java
- LogicStepEditor Testing to `87%` coverage
- ScriptEditor Testing to `85%` coverage
- ScriptRequestEditor Testing to `90%` coverage
=> Increment 1% more coverage

web/web_support/src/main/java/com/intuit/tank/admin/UserAdmin.java
**Add error message pop-up when attempting to delete user tied to existing resources**
This PR enhances the user deletion functionality in the Admin UI to provide better user experience and data integrity. Instead of hard-deleting users (which could cause database constraint violations), the system now validates resource ownership and uses anonymization to preserve referential integrity before the actual deletion of the user.
=> Add error message pop-up when attempting to delete user tied to existing resources
